# Generated by Django 4.2.2 on 2024-05-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_edit_description", "can edit description"),
                    ("can_change_category", "can change category"),
                    ("can_set_published", "can set published"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="признак публикации"),
        ),
    ]
